apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  labels:
    app.kubernetes.io/instance: asyncunitytemplate
    app.kubernetes.io/name: core
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll      
    keel.sh/pollSchedule: "@every 1m"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: asyncunitytemplate
      app.kubernetes.io/name: core
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: asyncunitytemplate
        app.kubernetes.io/name: core
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /test?string=test&number=5263
              port: http
          readinessProbe:
            httpGet:
              path: /test?string=test&number=5263
              port: http
          volumeMounts:
          - name: newsecret
            mountPath: "/src"
            readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: kubernetes-token
        secret:
          secretName: kubernetes-token
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
