apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-token
  namespace: {{ .Values.namespace }}
data:
  token: {{ .Values.secrets.token }}
type: kubernetes.io/dockerconfigjson