apiVersion: v1
kind: Service
metadata:
  name: core
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: asyncunitytemplate
    app.kubernetes.io/name: core
