{{- if and .Values.mongodb.resource.tls.enabled .Values.mongodb.resource.tls.useCertManager }}
# cert-manager resources
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tls-selfsigned-issuer
  namespace: {{ .Values.namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-selfsigned-ca
  namespace: {{ .Values.namespace }}
spec:
  isCA: true
  commonName: "*.{{ .Values.mongodb.resource.name }}-svc.{{ .Values.namespace }}.svc.cluster.local"
  dnsNames:
    - "*.{{ .Values.mongodb.resource.name }}-svc.{{ .Values.namespace }}.svc.cluster.local"
  secretName: {{ .Values.mongodb.resource.tls.caCertificateSecretRef }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: tls-selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tls-ca-issuer
  namespace: {{ .Values.namespace }}
spec:
  ca:
    secretName: {{ .Values.mongodb.resource.tls.caCertificateSecretRef }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-tls-certificate
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.mongodb.resource.tls.certificateKeySecretRef }}
  issuerRef:
    name: tls-ca-issuer
    kind: Issuer
  duration: {{ .Values.mongodb.resource.tls.certManager.certDuration | default "8760h" }}   # default to 365 days
  renewBefore: {{ .Values.mongodb.resource.tls.certManager.renewCertBefore | default "720h" }} # default to 30 days
  commonName: "*.{{ .Values.mongodb.resource.name }}-svc.{{ .Values.namespace }}.svc.cluster.local"
  dnsNames:
    - "*.{{ .Values.mongodb.resource.name }}-svc.{{ .Values.namespace }}.svc.cluster.local"
{{- if .Values.mongodb.resource.tls.useX509 }}
# Agent X509 certs
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: agent-certs
  namespace: {{ .Values.namespace }}
spec:
  commonName: mms-automation-agent
  dnsNames:
    - automation
  duration: 240h0m0s
  issuerRef:
    name: tls-ca-issuer
  renewBefore: 120h0m0s
  secretName: agent-certs
  subject:
    countries:
      - US
    localities:
      - NY
    organizationalUnits:
      - a-1635241837-m5yb81lfnrz
    organizations:
      - cluster.local-agent
    provinces:
      - NY
  usages:
    - digital signature
    - key encipherment
    - client auth
{{- end }}
{{- if .Values.mongodb.resource.tls.sampleX509User }}
# Client certs
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: x509-user-cert
  namespace: {{ .Values.namespace }}
spec:
  commonName: my-x509-user
  duration: 240h0m0s
  issuerRef:
    name: tls-ca-issuer
  renewBefore: 120h0m0s
  secretName: my-x509-user-cert
  subject:
    organizationalUnits:
      - organizationalunit
    organizations:
      - organization
  usages:
    - digital signature
    - client auth
{{- end }}
{{- end }}
{{- if .Values.mongodb.createResource }}
# mongodb resources
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.mongodb.resource.name }}
  namespace: {{ .Values.namespace }}
spec:
  members: {{ .Values.mongodb.resource.members }}
  type: ReplicaSet
  version: {{ .Values.mongodb.resource.version }}
  security:
    tls:
      enabled: {{ .Values.mongodb.resource.tls.enabled }}
      {{- if .Values.mongodb.resource.tls.enabled }}
      certificateKeySecretRef:
        name: {{ .Values.mongodb.resource.tls.certificateKeySecretRef }}
      caCertificateSecretRef:
        name: {{ .Values.mongodb.resource.tls.caCertificateSecretRef }}
      {{- end }}
    authentication:
      {{- if .Values.mongodb.resource.tls.useX509 }}
      modes: ["X509"]
      {{- else }}
      modes: ["SCRAM"]
      {{- end }}
  {{- if .Values.mongodb.resource.tls.sampleX509User }}
  users:
  - name: CN=my-x509-user,OU=organizationalunit,O=organization
    db: $external
    roles:
      - name: clusterAdmin
        db: admin
      - name: userAdminAnyDatabase
        db: admin
      - name: readWriteAnyDatabase
        db: admin
  {{- else }}
  users:
  {{- toYaml .Values.mongodb.resource.users | nindent 4 }}
  {{- end}}
{{- end }}