ingress:
  name: core
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/use-regex: 'true'
  hosts:
    - host: gdp2024-core.multiplayertournamentonline.fr
      path:  /()(.*)
      pathType: Prefix
      name: core
      port: 8000
    - host: gdp2024.multiplayertournamentonline.fr
      path:  /()(.*)
      pathType: Prefix
      name: frontend
      port: 80
    - host: gdp2024-instance.multiplayertournamentonline.fr
      path:  /()(.*)
      pathType: Prefix
      name: instance-fixe
      port: 8000
  tls: 
    - secretName: ingress-cert
      hosts:
        - multiplayertournamentonline.fr