name: 'Core'

on:
  push:
    branches: [ main ]
    paths:
      - core/**

  pull_request:
    branches: [ main ]
    paths:
      - core/**


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file core/Dockerfile -t asymetric-unity-core